services:
  - type: web
    name: spotify-indie-score
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python -m playwright install chromium
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PORT
        value: 10000
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /opt/render/project/.playwright