services:
  - type: web
    name: spotify-indie-score
    env: python
    buildCommand: pip install -r requirements.txt && playwright install chromium
    startCommand: gunicorn app.main:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:10000
    envVars:
      - key: PORT
        value: 10000
      - key: DEBUG_MODE
        value: "1"
      - key: LOG_LEVEL
        value: "debug"
    autoDeploy: true
    plan: free
    runtime: python
    region: oregon
